In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\AB\Desktop\Real_Estate_Investment_Advisor\data\raw\india_housing_prices.csv")

In [2]:
df

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status,Unnamed: 23
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move,NaN
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction,NaN
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move,NaN
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move,NaN
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,274.75,0.14,1995,...,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction,NaN
249996,249997,Tamil Nadu,Chennai,Locality_348,Apartment,1,2293,13.40,0.01,2013,...,8,10,Low,No,No,Playground,South,Broker,Ready_to_Move,NaN
249997,249998,Telangana,Warangal,Locality_225,Villa,4,2910,236.94,0.08,2003,...,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction,NaN
249998,249999,Odisha,Cuttack,Locality_138,Villa,1,1149,141.66,0.12,2007,...,3,7,Low,Yes,Yes,"Playground, Gym, Pool",South,Owner,Ready_to_Move,NaN
249999,250000,Haryana,Gurgaon,Locality_268,Independent House,3,4313,199.69,0.05,1990,...,10,6,Medium,No,No,"Gym, Garden",South,Owner,Under_Construction,NaN

In [3]:
print("Shape:", df.shape)

df.head()

Shape: (250000, 24)

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status,Unnamed: 23
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move,NaN
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction,NaN
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move,NaN
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move,NaN
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 24 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  object
 2   City                            250000 non-null  object
 3   Locality                        250000 non-null  object
 4   Property_Type                   250000 non-null  object
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  object
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  object
 17  Parking_Space                   250000 non-null  object
 18  Security                        250000 non-null  object
 19  Amenities                       250000 non-null  object
 20  Facing                          250000 non-null  object
 21  Owner_Type                      250000 non-null  object
 22  Availability_Status             250000 non-null  object
 23  Unnamed: 23                     0 non-null       float64
dtypes: float64(3), int64(9), object(12)
memory usage: 45.8+ MB

In [5]:
df.describe()

,ID,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Unnamed: 23
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,0.0
mean,125000.500000,2.999396,2749.813216,254.586854,0.130597,2006.520012,14.966800,15.503004,18.479988,5.499860,5.498016,NaN
std,72168.927986,1.415521,1300.606954,141.349921,0.130747,9.808575,8.948047,8.671618,9.808575,2.878639,2.871860,NaN
min,1.000000,1.000000,500.000000,10.000000,0.000000,1990.000000,0.000000,1.000000,2.000000,1.000000,1.000000,NaN
25%,62500.750000,2.000000,1623.000000,132.550000,0.050000,1998.000000,7.000000,8.000000,10.000000,3.000000,3.000000,NaN
50%,125000.500000,3.000000,2747.000000,253.870000,0.090000,2007.000000,15.000000,15.000000,18.000000,5.000000,5.000000,NaN
75%,187500.250000,4.000000,3874.000000,376.880000,0.160000,2015.000000,23.000000,23.000000,27.000000,8.000000,8.000000,NaN
max,250000.000000,5.000000,5000.000000,500.000000,0.990000,2023.000000,30.000000,30.000000,35.000000,10.000000,10.000000,NaN

In [6]:
df.isnull().sum()

ID                                     0
State                                  0
City                                   0
Locality                               0
Property_Type                          0
BHK                                    0
Size_in_SqFt                           0
Price_in_Lakhs                         0
Price_per_SqFt                         0
Year_Built                             0
Furnished_Status                       0
Floor_No                               0
Total_Floors                           0
Age_of_Property                        0
Nearby_Schools                         0
Nearby_Hospitals                       0
Public_Transport_Accessibility         0
Parking_Space                          0
Security                               0
Amenities                              0
Facing                                 0
Owner_Type                             0
Availability_Status                    0
Unnamed: 23                       250000
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.nunique()

ID                                250000
State                                 20
City                                  42
Locality                             500
Property_Type                          3
BHK                                    5
Size_in_SqFt                        4501
Price_in_Lakhs                     48700
Price_per_SqFt                       100
Year_Built                            34
Furnished_Status                       3
Floor_No                              31
Total_Floors                          30
Age_of_Property                       34
Nearby_Schools                        10
Nearby_Hospitals                      10
Public_Transport_Accessibility         3
Parking_Space                          2
Security                               2
Amenities                            325
Facing                                 4
Owner_Type                             3
Availability_Status                    2
Unnamed: 23                            0
dtype: int64

In [9]:
df.isnull().sum().sort_values(ascending=False)

Unnamed: 23                       250000
State                                  0
Availability_Status                    0
Owner_Type                             0
Facing                                 0
Amenities                              0
Security                               0
Parking_Space                          0
Public_Transport_Accessibility         0
Nearby_Hospitals                       0
Nearby_Schools                         0
Age_of_Property                        0
ID                                     0
Floor_No                               0
Furnished_Status                       0
Year_Built                             0
Price_per_SqFt                         0
Price_in_Lakhs                         0
Size_in_SqFt                           0
BHK                                    0
Property_Type                          0
Locality                               0
City                                   0
Total_Floors                           0
dtype: int64

In [10]:
df["ID"].duplicated().sum()

np.int64(0)

In [11]:
for col in df.columns:
    print(col, df[col].nunique())

ID 250000
State 20
City 42
Locality 500
Property_Type 3
BHK 5
Size_in_SqFt 4501
Price_in_Lakhs 48700
Price_per_SqFt 100
Year_Built 34
Furnished_Status 3
Floor_No 31
Total_Floors 30
Age_of_Property 34
Nearby_Schools 10
Nearby_Hospitals 10
Public_Transport_Accessibility 3
Parking_Space 2
Security 2
Amenities 325
Facing 4
Owner_Type 3
Availability_Status 2
Unnamed: 23 0

In [12]:
df.drop(columns=['Unnamed: 23'], inplace=True)

In [13]:
df.shape

(250000, 23)

In [14]:
df.isnull().sum()

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['ID'].duplicated().sum()

np.int64(0)

In [17]:
df.describe()

,ID,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,125000.500000,2.999396,2749.813216,254.586854,0.130597,2006.520012,14.966800,15.503004,18.479988,5.499860,5.498016
std,72168.927986,1.415521,1300.606954,141.349921,0.130747,9.808575,8.948047,8.671618,9.808575,2.878639,2.871860
min,1.000000,1.000000,500.000000,10.000000,0.000000,1990.000000,0.000000,1.000000,2.000000,1.000000,1.000000
25%,62500.750000,2.000000,1623.000000,132.550000,0.050000,1998.000000,7.000000,8.000000,10.000000,3.000000,3.000000
50%,125000.500000,3.000000,2747.000000,253.870000,0.090000,2007.000000,15.000000,15.000000,18.000000,5.000000,5.000000
75%,187500.250000,4.000000,3874.000000,376.880000,0.160000,2015.000000,23.000000,23.000000,27.000000,8.000000,8.000000
max,250000.000000,5.000000,5000.000000,500.000000,0.990000,2023.000000,30.000000,30.000000,35.000000,10.000000,10.000000

In [18]:
df['Actual_Price_per_SqFt'] = (df['Price_in_Lakhs'] * 100000) / df['Size_in_SqFt']

In [19]:
df['Actual_Price_per_SqFt'].describe()

count    250000.000000
mean      13058.281776
std       13071.850480
min         202.247191
25%        4802.839710
50%        9244.747594
75%       15987.388517
max       99182.000000
Name: Actual_Price_per_SqFt, dtype: float64